name: NickNames
version: 0.2.1
description: A plugin to change the nick names of users.
author: Halo4356
main: com.rafuse.minecraft.NickNames.Main
commands:
  nick:
    description: Set a nickname for a target user.
    usage: /nick [Player] [Nickname], /nick [Nickname]
  reset:
    description: Reset your or another person's nickname.
    usage: /reset, /reset [Player]
permissions:
  nicknames.nick:
    description: Permission on nick yourself
    default: op
  nicknames.nick.other:
    desciption: Permission to nick others
    default: op
  nicknames.reset:
    description: Reset your name to normal
    default: op
  nicknames.reset.other:
    description: Reset other peoples' names
    default: op